version: '3.8'
services:

  nginx:
   image: nginx:latest
   container_name: nginx
   ports:
       - "80:80"
       - "443:443"
volumes:
   - ./src:/var/www/html
   - ./nginx/first.domain.comn.conf:/etc/nginx/conf.d/first.domain.com.conf
   - ./nginx/second.domain.com.conf:/etc/nginx/conf.d/second.domain.com.conf
depends_on:
   - php
   - mysql
networks:
   - lar
   

mysql:
   image: mysql:latest
   restart: unless-stopped
   tty: true
   ports:
       - "3306:3306"
volumes:
   - db-data:/var/lib/mysql
   - ./mysql/my.cnf:/etc/mysql/my.cnf
environment:
        MYSQL_DATABASE: db-data
        MYSQL_USER: root
        MYSQL_PASSWORD: random
        MYSQL_ROOT_PASSWORD: random 
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql      
networks:
        - lar
        
myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
restart: always
depends_on:
            - mysql

php:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: php
volumes:
   - ./src:var/www/html
ports:
- "9000:9000"
networks:
        - lar
        
networks:
   lar:
 
volumes:
   db-data:
     
     
     
     
            